version: "3"
services:
  #  Create a service named db.
  lab-wp:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "balloon-shop"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=WebProgramming
      - POSTGRES_DB=balloon-shop
    #   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  lab-wp_postgres-data:


#Installation Directory: C:\Program Files\PostgreSQL\13
#Server Installation Directory: C:\Program Files\PostgreSQL\13
#Data Directory: C:\Program Files\PostgreSQL\13\data
#Database Port: 5432
#Database Superuser: postgres
#Operating System Account: NT AUTHORITY\NetworkService
#Database Service: postgresql-x64-13
#Command Line Tools Installation Directory: C:\Program Files\PostgreSQL\13
#pgAdmin4 Installation Directory: C:\Program Files\PostgreSQL\13\pgAdmin 4
#Stack Builder Installation Directory: C:\Program Files\PostgreSQL\13
